twig:
  file_name_pattern: "*.twig"
  # config/packages/twig.yaml
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    - "bootstrap_5_horizontal_layout.html.twig"

when@test:
  twig:
    strict_variables: true
