<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250326161208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application CHANGE job job INT DEFAULT NULL, CHANGE CV cv LONGTEXT NOT NULL, CHANGE Cover_Letter cover_letter LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1FBD8E0F8 FOREIGN KEY (job) REFERENCES job_offer (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX applications_ibfk_1 ON application');
        $this->addSql('CREATE INDEX IDX_A45BDDC1FBD8E0F8 ON application (job)');
        $this->addSql('DROP INDEX fk_application_user ON application');
        $this->addSql('CREATE INDEX IDX_A45BDDC18D93D649 ON application (user)');
        $this->addSql('ALTER TABLE attendance DROP FOREIGN KEY fk_attendance_employee');
        $this->addSql('ALTER TABLE attendance DROP FOREIGN KEY fk_attendance_employee');
        $this->addSql('ALTER TABLE attendance CHANGE user user INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D918D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_attendance_employee_idx ON attendance');
        $this->addSql('CREATE INDEX IDX_6DE30D918D93D649 ON attendance (user)');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_attendance_employee FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY fk_conge_employee');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY fk_conge_employee');
        $this->addSql('ALTER TABLE conge CHANGE user user INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED893488D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_conge_employee_idx ON conge');
        $this->addSql('CREATE INDEX IDX_2ED893488D93D649 ON conge (user)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT fk_conge_employee FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY fk_manager');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY fk_manager');
        $this->addSql('ALTER TABLE department CHANGE Name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AFA2425B9 FOREIGN KEY (manager) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_manager_idx ON department');
        $this->addSql('CREATE INDEX IDX_CD1DE18AFA2425B9 ON department (manager)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT fk_manager FOREIGN KEY (manager) REFERENCES user (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY fk_UID_Events');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY fk_UID_Events');
        $this->addSql('ALTER TABLE event CHANGE user user INT DEFAULT NULL, CHANGE Title title VARCHAR(255) NOT NULL, CHANGE Description description VARCHAR(255) NOT NULL, CHANGE Location location VARCHAR(255) NOT NULL, CHANGE Type type VARCHAR(255) NOT NULL, CHANGE DateAndTime date_and_time DATETIME NOT NULL, CHANGE NumberOfPlaces number_of_places INT NOT NULL, CHANGE isOnline is_online TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA78D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_uid_events ON event');
        $this->addSql('CREATE INDEX IDX_3BAE0AA78D93D649 ON event (user)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT fk_UID_Events FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY fk_formation_employee');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY fk_formation_employee');
        $this->addSql('ALTER TABLE formation CHANGE responsable responsable INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF52520D07 FOREIGN KEY (responsable) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_formation_employee_idx ON formation');
        $this->addSql('CREATE INDEX IDX_404021BF52520D07 ON formation (responsable)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT fk_formation_employee FOREIGN KEY (responsable) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY inscription_ibfk_2');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY inscription_ibfk_1');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY inscription_ibfk_2');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY inscription_ibfk_1');
        $this->addSql('ALTER TABLE inscription CHANGE formation formation INT DEFAULT NULL, CHANGE user user INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6404021BF FOREIGN KEY (formation) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D68D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX inscription_ibfk_1 ON inscription');
        $this->addSql('CREATE INDEX IDX_5E90F6D6404021BF ON inscription (formation)');
        $this->addSql('DROP INDEX inscription_ibfk_2 ON inscription');
        $this->addSql('CREATE INDEX IDX_5E90F6D68D93D649 ON inscription (user)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_ibfk_2 FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_ibfk_1 FOREIGN KEY (formation) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY interview_ibfk_1');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY Interview_Emplo_fk');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY interview_ibfk_1');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY Interview_Emplo_fk');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY fk_interview_application');
        $this->addSql('ALTER TABLE interview CHANGE application application INT DEFAULT NULL, CHANGE user user INT DEFAULT NULL, CHANGE Feedback feedback LONGTEXT DEFAULT NULL, CHANGE Status status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_CF1D3C348D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX interviews_ibfk_1 ON interview');
        $this->addSql('CREATE INDEX IDX_CF1D3C34A45BDDC1 ON interview (application)');
        $this->addSql('DROP INDEX interview_emplo_fk ON interview');
        $this->addSql('CREATE INDEX IDX_CF1D3C348D93D649 ON interview (user)');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT interview_ibfk_1 FOREIGN KEY (application) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT Interview_Emplo_fk FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT fk_interview_application FOREIGN KEY (application) REFERENCES application (id)');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY fk_job_offer_responsable');
        $this->addSql('ALTER TABLE job_offer CHANGE Description description LONGTEXT DEFAULT NULL, CHANGE Contract_Type contract_type VARCHAR(255) DEFAULT NULL, CHANGE Salary salary NUMERIC(10, 0) DEFAULT NULL');
        $this->addSql('DROP INDEX fk_job_offer_responsable ON job_offer');
        $this->addSql('CREATE INDEX IDX_288A3A4E8D93D649 ON job_offer (user)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT fk_job_offer_responsable FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY fkey_reclamation');
        $this->addSql('DROP INDEX fkey_sender ON message');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY fkey_reclamation');
        $this->addSql('ALTER TABLE message CHANGE reclamation reclamation INT DEFAULT NULL, CHANGE contenu contenu VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCE606404 FOREIGN KEY (reclamation) REFERENCES reclamation (id)');
        $this->addSql('DROP INDEX fkey_reclamation ON message');
        $this->addSql('CREATE INDEX IDX_B6BD307FCE606404 ON message (reclamation)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fkey_reclamation FOREIGN KEY (reclamation) REFERENCES reclamation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY fk_department');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY fk_projmanager');
        $this->addSql('DROP INDEX fk_projmanager ON project');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY fk_department');
        $this->addSql('ALTER TABLE project ADD User INT DEFAULT NULL, DROP Manager, CHANGE Name name VARCHAR(255) NOT NULL, CHANGE Description description VARCHAR(255) NOT NULL, CHANGE State state VARCHAR(255) DEFAULT NULL, CHANGE Department Department INT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE2DA17977 FOREIGN KEY (User) REFERENCES user (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE8240E25A FOREIGN KEY (Department) REFERENCES department (id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE2DA17977 ON project (User)');
        $this->addSql('DROP INDEX fk_department ON project');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE8240E25A ON project (Department)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT fk_department FOREIGN KEY (Department) REFERENCES department (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY fkey_employee');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY fkey_responsable');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY fkey_employee');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY fkey_responsable');
        $this->addSql('ALTER TABLE reclamation CHANGE user user INT DEFAULT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE60640452520D07 FOREIGN KEY (responsable) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE6064048D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('DROP INDEX fkey_responsable ON reclamation');
        $this->addSql('CREATE INDEX IDX_CE60640452520D07 ON reclamation (responsable)');
        $this->addSql('DROP INDEX fkey_employee ON reclamation');
        $this->addSql('CREATE INDEX IDX_CE6064048D93D649 ON reclamation (user)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT fkey_employee FOREIGN KEY (user) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT fkey_responsable FOREIGN KEY (responsable) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY fk_UID_Event');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY fk_ID_Evenement');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY fk_UID_Event');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY fk_ID_Evenement');
        $this->addSql('ALTER TABLE reservation CHANGE user user INT DEFAULT NULL, CHANGE event event INT DEFAULT NULL, CHANGE Type type VARCHAR(255) NOT NULL, CHANGE NombreDePlaces nombre_de_places INT NOT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849558D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849553BAE0AA7 FOREIGN KEY (event) REFERENCES event (id)');
        $this->addSql('DROP INDEX fk_uid_event ON reservation');
        $this->addSql('CREATE INDEX IDX_42C849558D93D649 ON reservation (user)');
        $this->addSql('DROP INDEX fk_id_evenement ON reservation');
        $this->addSql('CREATE INDEX IDX_42C849553BAE0AA7 ON reservation (event)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_UID_Event FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_ID_Evenement FOREIGN KEY (event) REFERENCES event (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY fk_assigned_to');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY fk_project_id');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY fk_assigned_to');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY fk_project_id');
        $this->addSql('ALTER TABLE task CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE priority priority VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2589EEAF91 FOREIGN KEY (assigned_to) REFERENCES user (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB252FB3D0EE FOREIGN KEY (project) REFERENCES project (id)');
        $this->addSql('DROP INDEX fk_assigned_to ON task');
        $this->addSql('CREATE INDEX IDX_527EDB2589EEAF91 ON task (assigned_to)');
        $this->addSql('DROP INDEX fk_project_id ON task');
        $this->addSql('CREATE INDEX IDX_527EDB252FB3D0EE ON task (project)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_assigned_to FOREIGN KEY (assigned_to) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_project_id FOREIGN KEY (project) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY fk_dep');
        $this->addSql('DROP INDEX UNIQ_8D93D64996901F54 ON user');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY fk_dep');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE first_name first_name VARCHAR(255) NOT NULL, CHANGE last_name last_name VARCHAR(255) NOT NULL, CHANGE number number VARCHAR(255) NOT NULL, CHANGE image_url image_url VARCHAR(255) DEFAULT \'https://i.ibb.co/S5rbLng/default-profile.jpg\' NOT NULL, CHANGE is_verified is_verified TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649CD1DE18A FOREIGN KEY (department) REFERENCES department (id)');
        $this->addSql('DROP INDEX fk_dep_idx ON user');
        $this->addSql('CREATE INDEX IDX_8D93D649CD1DE18A ON user (department)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT fk_dep FOREIGN KEY (department) REFERENCES department (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE body body LONGTEXT NOT NULL, CHANGE headers headers LONGTEXT NOT NULL, CHANGE queue_name queue_name VARCHAR(190) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1FBD8E0F8');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18D93D649');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1FBD8E0F8');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18D93D649');
        $this->addSql('ALTER TABLE application CHANGE job job INT NOT NULL, CHANGE cv CV TEXT NOT NULL, CHANGE cover_letter Cover_Letter TEXT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_a45bddc1fbd8e0f8 ON application');
        $this->addSql('CREATE INDEX applications_ibfk_1 ON application (job)');
        $this->addSql('DROP INDEX idx_a45bddc18d93d649 ON application');
        $this->addSql('CREATE INDEX fk_application_user ON application (user)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1FBD8E0F8 FOREIGN KEY (job) REFERENCES job_offer (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE attendance DROP FOREIGN KEY FK_6DE30D918D93D649');
        $this->addSql('ALTER TABLE attendance DROP FOREIGN KEY FK_6DE30D918D93D649');
        $this->addSql('ALTER TABLE attendance CHANGE user user INT NOT NULL');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_attendance_employee FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_6de30d918d93d649 ON attendance');
        $this->addSql('CREATE INDEX fk_attendance_employee_idx ON attendance (user)');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D918D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED893488D93D649');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED893488D93D649');
        $this->addSql('ALTER TABLE conge CHANGE user user INT NOT NULL, CHANGE status status VARCHAR(255) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT fk_conge_employee FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_2ed893488d93d649 ON conge');
        $this->addSql('CREATE INDEX fk_conge_employee_idx ON conge (user)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED893488D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18AFA2425B9');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18AFA2425B9');
        $this->addSql('ALTER TABLE department CHANGE name Name VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT fk_manager FOREIGN KEY (manager) REFERENCES user (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_cd1de18afa2425b9 ON department');
        $this->addSql('CREATE INDEX fk_manager_idx ON department (manager)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AFA2425B9 FOREIGN KEY (manager) REFERENCES user (id)');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA78D93D649');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA78D93D649');
        $this->addSql('ALTER TABLE event CHANGE user user INT NOT NULL, CHANGE title Title VARCHAR(60) NOT NULL, CHANGE description Description VARCHAR(300) NOT NULL, CHANGE location Location VARCHAR(100) NOT NULL, CHANGE type Type VARCHAR(50) NOT NULL, CHANGE date_and_time DateAndTime DATETIME NOT NULL, CHANGE number_of_places NumberOfPlaces INT NOT NULL, CHANGE is_online isOnline TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT fk_UID_Events FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_3bae0aa78d93d649 ON event');
        $this->addSql('CREATE INDEX fk_UID_Events ON event (user)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA78D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF52520D07');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF52520D07');
        $this->addSql('ALTER TABLE formation CHANGE responsable responsable INT NOT NULL, CHANGE title title VARCHAR(20) NOT NULL, CHANGE description description VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT fk_formation_employee FOREIGN KEY (responsable) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_404021bf52520d07 ON formation');
        $this->addSql('CREATE INDEX fk_formation_employee_idx ON formation (responsable)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF52520D07 FOREIGN KEY (responsable) REFERENCES user (id)');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D6404021BF');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D68D93D649');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D6404021BF');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D68D93D649');
        $this->addSql('ALTER TABLE inscription CHANGE formation formation INT NOT NULL, CHANGE user user INT NOT NULL, CHANGE status status VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_ibfk_2 FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_ibfk_1 FOREIGN KEY (formation) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5e90f6d68d93d649 ON inscription');
        $this->addSql('CREATE INDEX inscription_ibfk_2 ON inscription (user)');
        $this->addSql('DROP INDEX idx_5e90f6d6404021bf ON inscription');
        $this->addSql('CREATE INDEX inscription_ibfk_1 ON inscription (formation)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6404021BF FOREIGN KEY (formation) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D68D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_CF1D3C348D93D649');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_CF1D3C34A45BDDC1');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_CF1D3C348D93D649');
        $this->addSql('ALTER TABLE interview CHANGE application application INT NOT NULL, CHANGE user user INT NOT NULL, CHANGE feedback Feedback TEXT DEFAULT NULL, CHANGE status Status VARCHAR(255) DEFAULT \'Scheduled\'');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT interview_ibfk_1 FOREIGN KEY (application) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT Interview_Emplo_fk FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_cf1d3c34a45bddc1 ON interview');
        $this->addSql('CREATE INDEX interviews_ibfk_1 ON interview (application)');
        $this->addSql('DROP INDEX idx_cf1d3c348d93d649 ON interview');
        $this->addSql('CREATE INDEX Interview_Emplo_fk ON interview (user)');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_CF1D3C34A45BDDC1 FOREIGN KEY (application) REFERENCES application (id)');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_CF1D3C348D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E8D93D649');
        $this->addSql('ALTER TABLE job_offer CHANGE description Description TEXT DEFAULT NULL, CHANGE contract_type Contract_Type VARCHAR(100) DEFAULT NULL, CHANGE salary Salary NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('DROP INDEX idx_288a3a4e8d93d649 ON job_offer');
        $this->addSql('CREATE INDEX fk_job_offer_responsable ON job_offer (user)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E8D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FCE606404');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FCE606404');
        $this->addSql('ALTER TABLE message CHANGE reclamation reclamation INT NOT NULL, CHANGE contenu contenu VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fkey_reclamation FOREIGN KEY (reclamation) REFERENCES reclamation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fkey_sender ON message (user)');
        $this->addSql('DROP INDEX idx_b6bd307fce606404 ON message');
        $this->addSql('CREATE INDEX fkey_reclamation ON message (reclamation)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCE606404 FOREIGN KEY (reclamation) REFERENCES reclamation (id)');
        $this->addSql('ALTER TABLE messenger_messages CHANGE body body LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE headers headers LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE queue_name queue_name VARCHAR(190) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE2DA17977');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE8240E25A');
        $this->addSql('DROP INDEX IDX_2FB3D0EE2DA17977 ON project');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE8240E25A');
        $this->addSql('ALTER TABLE project ADD Manager INT NOT NULL, DROP User, CHANGE name Name VARCHAR(20) NOT NULL, CHANGE description Description VARCHAR(60) NOT NULL, CHANGE state State VARCHAR(20) DEFAULT NULL, CHANGE Department Department INT NOT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT fk_department FOREIGN KEY (Department) REFERENCES department (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT fk_projmanager FOREIGN KEY (Manager) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_projmanager ON project (Manager)');
        $this->addSql('DROP INDEX idx_2fb3d0ee8240e25a ON project');
        $this->addSql('CREATE INDEX fk_department ON project (Department)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE8240E25A FOREIGN KEY (Department) REFERENCES department (id)');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_CE60640452520D07');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_CE6064048D93D649');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_CE60640452520D07');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_CE6064048D93D649');
        $this->addSql('ALTER TABLE reclamation CHANGE user user INT NOT NULL, CHANGE titre titre VARCHAR(50) NOT NULL, CHANGE description description VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT fkey_employee FOREIGN KEY (user) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT fkey_responsable FOREIGN KEY (responsable) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_ce6064048d93d649 ON reclamation');
        $this->addSql('CREATE INDEX fkey_employee ON reclamation (user)');
        $this->addSql('DROP INDEX idx_ce60640452520d07 ON reclamation');
        $this->addSql('CREATE INDEX fkey_responsable ON reclamation (responsable)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE60640452520D07 FOREIGN KEY (responsable) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE6064048D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C849558D93D649');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C849553BAE0AA7');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C849558D93D649');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C849553BAE0AA7');
        $this->addSql('ALTER TABLE reservation CHANGE user user INT NOT NULL, CHANGE event event INT NOT NULL, CHANGE type Type VARCHAR(50) NOT NULL, CHANGE nombre_de_places NombreDePlaces INT NOT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_UID_Event FOREIGN KEY (user) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_ID_Evenement FOREIGN KEY (event) REFERENCES event (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_42c849553bae0aa7 ON reservation');
        $this->addSql('CREATE INDEX fk_ID_Evenement ON reservation (event)');
        $this->addSql('DROP INDEX idx_42c849558d93d649 ON reservation');
        $this->addSql('CREATE INDEX fk_UID_Event ON reservation (user)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849558D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849553BAE0AA7 FOREIGN KEY (event) REFERENCES event (id)');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB2589EEAF91');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB252FB3D0EE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB2589EEAF91');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB252FB3D0EE');
        $this->addSql('ALTER TABLE task CHANGE description description TEXT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT \'To Do\' NOT NULL, CHANGE priority priority VARCHAR(255) DEFAULT \'Medium\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_assigned_to FOREIGN KEY (assigned_to) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_project_id FOREIGN KEY (project) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_527edb2589eeaf91 ON task');
        $this->addSql('CREATE INDEX fk_assigned_to ON task (assigned_to)');
        $this->addSql('DROP INDEX idx_527edb252fb3d0ee ON task');
        $this->addSql('CREATE INDEX fk_project_id ON task (project)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2589EEAF91 FOREIGN KEY (assigned_to) REFERENCES user (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB252FB3D0EE FOREIGN KEY (project) REFERENCES project (id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649CD1DE18A');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649CD1DE18A');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE password password VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE first_name first_name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE last_name last_name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE number number VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE image_url image_url VARCHAR(255) DEFAULT \'https://i.ibb.co/S5rbLng/default-profile.jpg\' NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE is_verified is_verified TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT fk_dep FOREIGN KEY (department) REFERENCES department (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64996901F54 ON user (number)');
        $this->addSql('DROP INDEX idx_8d93d649cd1de18a ON user');
        $this->addSql('CREATE INDEX fk_dep_idx ON user (department)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649CD1DE18A FOREIGN KEY (department) REFERENCES department (id)');
    }
}
