controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
2fa_login:
    path: /2fa
    defaults:
        _controller: scheb_two_factor.form_controller::form
